### PR TITLE
Make replace-by-fee honest

### PR DESCRIPTION
**Pull request by aalness**

### CODE REVIEW

**Comment by btcdrak** [comment]
Can you explain more about how this makes it more honest please?

**Comment by petertodd** [comment]
I think it'd be better to have a simpler version that doesn't try to be clever with chains of transactions, and simply only allows replacement when all outputs are unspent. Significantly less code, and 95% of the functionality.

**Comment by aalness** [comment]
@btcdrak balances associated with unspent outputs attached to transaction(s) being evicted will have to be honored in full (or better) by the replacement transaction. Peter probably phrases the concept a bit better w/ "first-seen safe rbf."

@petertodd definitely seems simpler.

**Comment by coblee** [comment]
@petertodd That's an neat idea. So to insure that an unconfirmed transaction is locked in, the merchant would just add a child transaction spending its output. And if that transaction is propagated to most of the network, then it's pretty good bet that the payment will confirm. The side benefit of this change is that replacing a transaction will never invalidate any other transaction in the mempool. I like it.

**Comment by petertodd** [comment]
@coblee Yeah, I think we have reasonable consensus that this "first-seen safe rbf" has no negative effects on zeroconf, and it certainly makes things better re: fees, which I've had a bunch of requests for. As it'll let inputs get replaced, an easy way to increase a fee very efficiently when you have >1 inputs is to replace one input with a higher valued input, and then increase the change output correspondingly, minus the bump in fee. Equally, it's useful with @luke-jr's CPFP on the merchant side - just increase the fee paid by the child tx if the parent isn't getting mined fast enough.

I probably even have code implementing this lying around somewhere already; I'll dig that up soon and submit a pull-req.

**Pull request closed without merging**
