### PR TITLE
Add more spam address's to the Blacklist

### PR DESCRIPTION
**Pull request by elichai**
I added'd  the SatoshiBones spam address and the LukyBit spam address to the Blacklist function

### CODE REVIEW

**Comment by petertodd** [comment]
Have you submitted this to Luke-Jr?

Out of curiosity, are you actually using this patch for mining?

**Comment by elichai** [comment]
First, I submited it already to Luke-Jr.
Second he already had some more spam address's that you haven't.

I'm not a miner, I'm just working on anti-double-spend script and I talk to some of the pools and eligius told me they use Luke-Jr script so I thought maybe one of the pools uses your's script too.

and when i searched a little about address's I found out you two missed this one, so I made a pull request

**Comment by petertodd** [comment]
You'd probably be better off taking a more recent version of the Eligius fork and re-rebasing the replace-by-fee changes on top of it; this branch is pretty out of date.

**Comment by elichai** [comment]
yeah, that's what I thought, But I made the pull request just in case anyone using this branch and backporting it.
But ok.

**Comment by petertodd** [comment]
Let me know if you do a re-rebase so I can point others to it.

**Pull request closed without merging**
